import {
  HiOutlineHome,
  HiOutlineTemplate,
  HiOutlineTruck,
  HiOutlineChartBar,
  HiOutlineCog,
  HiOutlineUserCircle,
  HiOutlineCreditCard,
  HiOutlineLogout,
} from "react-icons/hi";

export const SidebarNavigation = [
  {
    name: "Home",
    href: "/home",
    type: "page",
    icon: HiOutlineHome,
    current: false,
    first: false,
  },
  {
    name: "Temas",
    type: "page",
    icon: HiOutlineTemplate,
    current: true,
    first: false,
    children: [
      { name: "Loja", href: "/loja", current: false },
      { name: "Checkout", href: "/checkout", current: false },
    ],
  },
  {
    name: "Rastreamento",
    href: "#",
    type: "page",
    icon: HiOutlineTruck,
    current: false,
    first: false,
  },
  {
    name: "Análises",
    href: "#",
    type: "page",
    icon: HiOutlineChartBar,
    current: false,
    first: false,
  },
  {
    name: "Configurações",
    href: "/configuracoes",
    type: "user",
    icon: HiOutlineCog,
    current: false,
    first: true,
  },
  {
    name: "Minha conta",
    href: "/minha-conta",
    type: "user",
    icon: HiOutlineUserCircle,
    current: false,
    first: false,
  },
  {
    name: "Assinatura",
    href: "/assinatura",
    type: "user",
    icon: HiOutlineCreditCard,
    current: false,
    first: false,
  },
  {
    name: "Sair",
    href: "#",
    type: "user",
    icon: HiOutlineLogout,
    current: false,
    first: false,
  },
];
